[workspace]
members = [
    "crates/azuro_client",
    "crates/execution",
    "crates/monitoring",
    "crates/normalization",
    "crates/orchestrator",
    "crates/sx_client",
    "crates/tools",
]
resolver = "2"
