name: secrets-smoke
on:
  workflow_dispatch:
  schedule:
    - cron: '15 */6 * * *'
permissions:
  contents: read
jobs:
  vault-smoke:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-vault@v1
        with:
          vault-version: 1.15.3
      - name: Vault secrets smoke
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          SX_ROLE_ID: ${{ secrets.SX_TRADER_ROLE_ID }}
          SX_SECRET_ID: ${{ secrets.SX_TRADER_SECRET_ID }}
          AZURO_ROLE_ID: ${{ secrets.AZURO_TRADER_ROLE_ID }}
          AZURO_SECRET_ID: ${{ secrets.AZURO_TRADER_SECRET_ID }}
          SX_SECRET_PATH: secret/data/trading/sx/wallet
          AZURO_SECRET_PATH: secret/data/trading/azuro/wallet
        run: |
          chmod +x scripts/vault_smoke.sh
          ./scripts/vault_smoke.sh
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: secrets-audit
          path: logs/secrets_audit.json
