[package]
name = "orchestrator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
sha2 = "0.10"
thiserror = "1.0"
tracing = "0.1"

[dev-dependencies]
tempfile = "3.8"
