providers:
  sx:
    name: "SX Network"
    execution_mode: "partial_fill"
    odds_slippage:
      clamp_min: 0.0
      clamp_max: 0.03
    odds_ladder:
      min: 1.01
      max: 20.0
      step: 0.01
    endpoints:
      rest:
        market_data: "https://api.sx.bet/markets"
        orders: "https://api.sx.bet/trading"
      websocket:
        trading: "wss://api.sx.bet/ws"
    heartbeat:
      interval_ms: 5000
      grace_missed_beats: 1
    betting_delay_ms: 1000
