---
version: 1
environment: prod
notes: |
  Configuration production pour l’arb SX Rollup ↔ Azuro (Arbitrum One).
  Mode cash-only, jambe SX exécutée en premier puis hedge Azuro sans bridge runtime.
chains:
  sx_rollup:
    name: "SX Rollup"
    network: "Arbitrum Orbit"
    chain_id: 1257787536744045
    currency: USDC
    rpc:
      http:
        url: "https://rpc.sx.bet"
        provider: "SX Network"
        expected_latency_ms: 190
      websocket:
        url: "wss://api.sx.bet/ws"
        provider: "SX Network"
        expected_latency_ms: 210
    rest_api:
      market_data:
        url: "https://api.sx.bet/markets"
        expected_latency_ms: 220
      orders:
        url: "https://api.sx.bet/trading"
        expected_latency_ms: 220
    execution:
      ttl_ms: 800
      odds_slippage_bps: 200
      heartbeat_interval_ms: 5000
      betting_delay_ms: 1000
    bank_live_source:
      type: onchain
      contract_address: "0xA4b5D7cE06bb3A02EDc69cA1CB78D7a6F047D52e"
  arbitrum_one:
    name: "Arbitrum One"
    chain_id: 42161
    currency: USDC
    rpc:
      http:
        url: "https://arb1.arbitrum.io/rpc"
        provider: "Arbitrum Foundation"
        expected_latency_ms: 180
      websocket:
        url: "wss://arb1.arbitrum.io/ws"
        provider: "Arbitrum Foundation"
        expected_latency_ms: 200
    rest_api:
      azuro_graphql:
        url: "https://api.azuro.org/graphql"
        expected_latency_ms: 240
    execution:
      ttl_ms: 2500
      private_tx_relay: "https://relay.azuro.org"
    bank_live_source:
      type: onchain
      contract_address: "0x6E2E1e9cEa0F23E524CF969f4fD6C9b7E8B683Ff"
wallets:
  sx_rollup:
    address: "0x7F2F9E8d53AE9E9e6c820d10C011c945B2E8D14E"
    signer_env: "SX_ROLLUP_PROD_PK"
    min_prefunded_bank_usdc: "3x stake_max"
  arbitrum_one:
    address: "0x1b1Ff5fbb5a857cD2Bd1D773FC1d68128EC5D8f6"
    signer_env: "AZURO_PROD_PK"
    min_prefunded_bank_usdc: "3x stake_max"
latency_targets:
  market_data_p95_ms: 250
  websocket_heartbeat_ms: 5000
  sequencer_health_poll_ms: 10000
risk_limits:
  stake_pct_cap: 0.015
  stake_min_usdc: 50
  stake_max_usdc: 1500
  threshold_net_pct: 0.015
  delta_odd_reject: 0.02
  fill_ratio_pause_threshold_pct: 60
  accept_time_pause_threshold_p95_ms: 1000
compliance:
  bridging_allowed_during_execution: false
  real_money_flag: true
